const AboutUs =
    [{
        "componentName": "UFlexLayout",
        "containerId": "4ade3b4e-6ea4-4fe5-b207-7c786b6caf03",
        "backgroundColor": "",
        "flexDirection": "row",
        "boxNumber": 1,
        "gap": 1,
        "containerScale": [],
        "containerBackground": [],
        "minHeight": 60,
        "maxHeight": 100,
        "width": 100,
        "minWidth": null,
        "maxWidth": 100,
        "justifyContent": "stretch",
        "alignItems": "stretch",
        "childHoverEffect": "none",
        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
        "animate": "",
        "hoverEffect": "none",
        "position": "relative",
        "borderStyle": "solid",
        "float": "none",
        "containerScale0": 1,
        "childNodes": [[{
            "componentName": "UNav",
            "containerId": "d6e48dc6-ee5a-45c2-9323-8b958369b874",
            "dataSource": "2",
            "routeConfiguration": [{"name": "Home", "path": "/home"}, {
                "name": "Service",
                "value": "",
                "path": "/service"
            }, {"name": "Track Peference", "value": "", "path": "/track-peference"}, {
                "name": "About Us",
                "value": "",
                "path": "/about-us"
            }, {"name": "Contacts", "value": "", "path": "/contacts"}],
            "backgroundColor": "",
            "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
            "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
            "animate": "",
            "hoverEffect": "none",
            "position": "relative",
            "float": "none",
            "color": "rgba(255, 255, 255, 1)",
            "bottomBorderSize": 1,
            "bottomBorderColor": "rgba(225, 225, 225, 1)",
            "hoverColor": "rgba(230, 230, 230, 0.5)",
            "logoUrl": "/assets/img.png"
        }]],
        "backgroundImageUrl": "/assets/img.png",
        "mountedCallBack": {"type": "event", "event": "", "eventId": "5ff38bf6-cd34-4774-b08a-426f6a83bc2e"},
        "clickChildCallBack": {"type": "event", "event": "", "eventId": "fb315c46-0ed6-4267-be0e-0b3c1c6b77e0"}
    }, {
        "componentName": "UFlexLayout",
        "containerId": "e5fd3d43-4918-421a-9547-d463f57ec415",
        "backgroundColor": "",
        "flexDirection": "row",
        "boxNumber": 1,
        "gap": 1,
        "containerScale": [],
        "containerBackground": [],
        "minHeight": 10,
        "maxHeight": 100,
        "width": 100,
        "minWidth": 10,
        "maxWidth": 100,
        "justifyContent": "center",
        "alignItems": "stretch",
        "childHoverEffect": "none",
        "borderStyle": "solid",
        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 2},
        "animate": "",
        "hoverEffect": "none",
        "position": "relative",
        "float": "none",
        "containerScale0": 1,
        "borderShow": ["top", "left", "right"],
        "borderWidth": 2,
        "borderColor": "rgba(218, 218, 218, 0.5)",
        "childNodes": [[{
            "componentName": "UTitle",
            "containerId": "b0530090-d169-4f33-b28a-a34471e17580",
            "title": "About us",
            "dynamicTag": "h1",
            "color": "var(--el-text-color-primary)",
            "textAlignType": "center",
            "fontSize": "revert",
            "fontWeight": "normal",
            "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
            "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 1, "marginBottom": 1},
            "animate": "",
            "hoverEffect": "none",
            "position": "static",
            "float": "none",
            "fontFamily": "Azonix"
        }]],
        "mountedCallBack": {"type": "event", "event": "", "eventId": "74134cdd-7ffb-4f79-9c67-7dc9f2934ce1"},
        "clickChildCallBack": {"type": "event", "event": "", "eventId": "b0773dfe-71d5-4693-8dbe-aa582f49632c"}
    }, {
        "componentName": "UFlexLayout",
        "containerId": "b65d2352-247d-46fb-8294-18b23f8c4773",
        "backgroundColor": "",
        "flexDirection": "row",
        "boxNumber": 1,
        "gap": 1,
        "containerScale": [],
        "containerBackground": [],
        "minHeight": 80,
        "maxHeight": 100,
        "width": 100,
        "minWidth": 50,
        "maxWidth": 100,
        "justifyContent": "stretch",
        "alignItems": "stretch",
        "childHoverEffect": "none",
        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 2, "marginBottom": "2"},
        "animate": "",
        "hoverEffect": "none",
        "position": "static",
        "borderStyle": "solid",
        "float": "none",
        "containerScale0": 1,
        "childNodes": [[{
            "componentName": "UFlexLayout",
            "containerId": "23210996-9c6e-4493-a1a6-74943654dd99",
            "backgroundColor": "",
            "flexDirection": "row",
            "boxNumber": 1,
            "gap": 1,
            "containerScale": [],
            "containerBackground": [],
            "minHeight": 50,
            "maxHeight": 100,
            "width": 100,
            "minWidth": 50,
            "maxWidth": 67,
            "justifyContent": "stretch",
            "alignItems": "stretch",
            "childHoverEffect": "none",
            "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
            "containerMargin": {"marginLeft": "auto", "marginRight": "auto", "marginTop": 0, "marginBottom": 0},
            "animate": "",
            "hoverEffect": "none",
            "position": "static",
            "borderStyle": "solid",
            "float": "none",
            "containerScale0": 1,
            "childNodes": [[{
                "componentName": "UFlexLayout",
                "containerId": "bc7c6144-2d30-4d57-b3d1-93ffb240ab24",
                "backgroundColor": "",
                "flexDirection": "row",
                "boxNumber": 2,
                "gap": 1,
                "containerScale": [],
                "containerBackground": [],
                "minHeight": 29,
                "maxHeight": 100,
                "width": 100,
                "minWidth": 50,
                "maxWidth": 100,
                "justifyContent": "stretch",
                "alignItems": "stretch",
                "childHoverEffect": "none",
                "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 2, "paddingBottom": 0},
                "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                "animate": "",
                "hoverEffect": "none",
                "position": "static",
                "borderStyle": "solid",
                "float": "none",
                "containerScale0": 2,
                "containerScale1": 1,
                "childNodes": [[{
                    "componentName": "UFlexLayout",
                    "containerId": "13ace03a-6f10-4c9b-947e-62dec0ee2110",
                    "backgroundColor": "",
                    "flexDirection": "row",
                    "boxNumber": 1,
                    "gap": 1,
                    "containerScale": [],
                    "containerBackground": [],
                    "minHeight": 22,
                    "maxHeight": 100,
                    "width": 100,
                    "minWidth": 29,
                    "maxWidth": 100,
                    "justifyContent": "stretch",
                    "alignItems": "stretch",
                    "childHoverEffect": "none",
                    "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": "0", "paddingBottom": 0},
                    "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                    "animate": "",
                    "hoverEffect": "none",
                    "position": "static",
                    "borderStyle": "solid",
                    "float": "none",
                    "containerScale0": 1,
                    "childNodes": [[{
                        "componentName": "UTitle",
                        "containerId": "d2e26be8-de2c-41b1-b354-5c491460f8f9",
                        "title": "Oriental Victoria Energy E&T Co., Ltd (OVET)",
                        "dynamicTag": "h1",
                        "color": "rgba(84, 102, 133, 1)",
                        "textAlignType": "start",
                        "fontSize": "revert",
                        "fontWeight": "normal",
                        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 2},
                        "animate": "",
                        "hoverEffect": "none",
                        "position": "static",
                        "float": "none"
                    }, {
                        "componentName": "UList",
                        "containerId": "7e5f197e-72bf-471e-a5ee-3b3611bc137d",
                        "listItemConfiguration": [],
                        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                        "animate": "",
                        "hoverEffect": "none",
                        "position": "static",
                        "float": "none"
                    }, {
                        "componentName": "UList",
                        "containerId": "9352e50a-9ddc-4001-9761-90d205e3a0d8",
                        "listItemConfiguration": [{"value": "Consultation & Engineering oriented Special Task Force in Energy Industry."}, {
                            "value": "Complete disciplines covering Oil & Gas, Renewable Energy, CCUS/CCS & System Application.",
                            "children": [],
                            "color": "rgba(137, 140, 145, 1)"
                        }, {
                            "value": "Life-circle scope as Client’s Long-term Partner, providing service of Feasibility Study, FEED, Basic",
                            "children": [{
                                "value": "Design, Detail Design, Risk Assessment, Topic Study, IT System, O&M Support, etc.",
                                "children": []
                            }],
                            "color": "rgba(137, 140, 145, 1)"
                        }, {
                            "value": "Equipped with State-of-the-art Industry Software. Self-developed Industry & Technical System.",
                            "children": [{
                                "value": "Project/Operation System service. Life Circle PM Sys, Cost Estimation Sys, Commissioning Sys…",
                                "children": []
                            }],
                            "color": "rgba(137, 140, 145, 1)"
                        }, {
                            "value": "Profound Project Track Record for Renown Clients globally.",
                            "children": [],
                            "color": "rgba(137, 140, 145, 1)"
                        }],
                        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                        "animate": "",
                        "hoverEffect": "none",
                        "position": "static",
                        "float": "none",
                        "fontSize": "none",
                        "markerColor": "rgba(84, 102, 133, 1)",
                        "fontWeight": "normal"
                    }, {
                        "componentName": "UList",
                        "containerId": "8886353c-8240-48bf-a539-7059488c3727",
                        "listItemConfiguration": [{
                            "value": "Management System ISO 9001 / 14001 / OHSAS 18001 Certified",
                            "color": "rgba(0, 0, 0, 1)"
                        }, {
                            "value": "Best understanding of International codes, JIS, EU, BS, ASTM, ASME, ISO…",
                            "children": [],
                            "color": "rgba(137, 140, 145, 1)"
                        }, {
                            "value": "Strong Partners all over the World, Labs, Test Centers, Universities, etc.",
                            "children": [],
                            "color": "rgba(137, 140, 145, 1)"
                        }, {
                            "value": "Service presence via global Representative Office, Engineering Center, facilitating service quality.",
                            "children": [],
                            "color": "rgba(137, 140, 145, 1)"
                        }],
                        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 1, "marginBottom": 0},
                        "animate": "",
                        "hoverEffect": "none",
                        "position": "static",
                        "float": "none",
                        "fontSize": "none",
                        "markerColor": "rgba(84, 102, 133, 1)",
                        "fontWeight": "normal"
                    }]],
                    "mountedCallBack": {
                        "type": "event",
                        "event": "",
                        "eventId": "feb9c94c-9d53-4bfd-b42d-6d333e3d2b0b"
                    },
                    "clickChildCallBack": {
                        "type": "event",
                        "event": "",
                        "eventId": "dc9305a8-ed04-4a16-bd67-9c0b6cd13844"
                    }
                }], [{
                    "componentName": "CombiningImages",
                    "containerId": "bb0f1c6a-be10-42c7-bbd2-df083dea7d0f",
                    "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                    "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                    "animate": [],
                    "hoverEffect": "none",
                    "position": "static",
                    "float": "none"
                }]],
                "mountedCallBack": {"type": "event", "event": "", "eventId": "284d5fd3-674c-4633-a681-d85961117f08"},
                "clickChildCallBack": {"type": "event", "event": "", "eventId": "c6433bab-6ba1-4571-95ef-3178de4cfa45"}
            }, {
                "componentName": "UInlineLayout",
                "containerId": "bcc21e7e-9e38-4e73-82f2-8651df0dd36b",
                "minHeight": 3,
                "maxHeight": 100,
                "width": 100,
                "minWidth": 50,
                "maxWidth": 100,
                "justifyContent": "center",
                "alignItems": "center",
                "childHoverEffect": "none",
                "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 2, "marginBottom": "0"},
                "animate": "",
                "hoverEffect": "none",
                "position": "static",
                "borderStyle": "solid",
                "float": "none",
                "childNodes": [{
                    "componentName": "UButton",
                    "containerId": "4345ec6f-1e0a-4983-8f65-a896ba7e4dd4",
                    "type": "default",
                    "icon": "",
                    "backgroundColor": "",
                    "width": 100,
                    "height": 40,
                    "textContent": "READ MORE",
                    "color": "rgba(0, 0, 0, 1)",
                    "textAlignType": "center",
                    "fontSize": "medium",
                    "fontWeight": "bold",
                    "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                    "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                    "animate": "",
                    "hoverEffect": "none",
                    "position": "static",
                    "float": "none",
                    "borderRadius": 30,
                    "minHeight": 5,
                    "minWidth": 10,
                    "maxWidth": 10,
                    "maxHeight": 100,
                    "borderWidth": 2,
                    "borderColor": "rgba(0, 0, 0, 1)",
                    "clickEvent": {"type": "event", "event": "", "eventId": "66b21b1a-5ac7-4cbc-a37f-9baae7af3911"}
                }]
            }]],
            "mountedCallBack": {"type": "event", "event": "", "eventId": "98e8f466-bc50-4042-8d58-cf98661ad59c"},
            "clickChildCallBack": {"type": "event", "event": "", "eventId": "5d16e361-913c-4d9d-b21d-5d41dc0bd80b"}
        }]],
        "mountedCallBack": {"type": "event", "event": "", "eventId": "ca0d2af3-2a7d-4cfa-aa85-32f2a1666298"},
        "clickChildCallBack": {"type": "event", "event": "", "eventId": "bf6a9f7d-d9a8-4a01-8580-e433afe7f9cc"}
    }, {
        "componentName": "UFlexLayout",
        "containerId": "3a8cf7b8-a50a-4d85-9e8f-307c0785c372",
        "backgroundColor": "rgba(0, 0, 0, 1)",
        "flexDirection": "row",
        "boxNumber": 1,
        "gap": 1,
        "containerScale": [],
        "containerBackground": [],
        "minHeight": 10,
        "maxHeight": 100,
        "width": 100,
        "minWidth": 10,
        "maxWidth": 100,
        "justifyContent": "stretch",
        "alignItems": "stretch",
        "childHoverEffect": "none",
        "borderStyle": "solid",
        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": "0", "paddingBottom": "0"},
        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
        "animate": "",
        "hoverEffect": "none",
        "position": "static",
        "float": "none",
        "containerScale0": 1,
        "borderColor": "rgba(184, 184, 184, 0.5)",
        "borderWidth": 1,
        "borderShow": ["top", "left", "right"],
        "childNodes": [[{
            "componentName": "UFlexLayout",
            "containerId": "4b00fd78-b16a-4923-aa4b-2f847978ffff",
            "backgroundColor": "",
            "flexDirection": "row",
            "boxNumber": 2,
            "gap": 1,
            "containerScale": [],
            "containerBackground": [],
            "minHeight": 10,
            "maxHeight": 100,
            "width": 100,
            "minWidth": 0,
            "maxWidth": 67,
            "justifyContent": "stretch",
            "alignItems": "center",
            "childHoverEffect": "none",
            "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": "1", "paddingBottom": "1"},
            "containerMargin": {"marginLeft": "auto", "marginRight": "auto", "marginTop": 0, "marginBottom": 0},
            "animate": "",
            "hoverEffect": "none",
            "position": "static",
            "float": "none",
            "childNodes": [[{
                "componentName": "UFlexLayout",
                "containerId": "a102bdd2-7682-4867-8e94-13a3531dca6d",
                "backgroundColor": "",
                "flexDirection": "row",
                "boxNumber": 1,
                "gap": 1,
                "containerScale": [],
                "containerBackground": [],
                "minHeight": 0,
                "maxHeight": 100,
                "width": 100,
                "minWidth": 10,
                "maxWidth": 100,
                "justifyContent": "flex-start",
                "alignItems": "center",
                "childHoverEffect": "none",
                "borderStyle": "solid",
                "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                "animate": "",
                "hoverEffect": "none",
                "position": "static",
                "float": "none",
                "containerScale0": 1,
                "childNodes": [[{
                    "componentName": "UImage",
                    "containerId": "bed4a5ba-5b60-4958-b753-d549ba2c7d24",
                    "imageList": [{
                        "url": "https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg",
                        "uid": 1711522124350,
                        "status": "success"
                    }],
                    "local": "1",
                    "imageUrl": "/assets/img.png",
                    "width": 60,
                    "minWidth": 0,
                    "maxWidth": 100,
                    "minHeight": 0,
                    "maxHeight": 100,
                    "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                    "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 1, "marginBottom": 0},
                    "animate": "",
                    "hoverEffect": "none",
                    "position": "static",
                    "float": "none"
                }]],
                "mountedCallBack": {"type": "event", "event": "", "eventId": "c642ee04-f9e0-47a8-a014-0e5270264dc7"},
                "clickChildCallBack": {"type": "event", "event": "", "eventId": "b28eba14-c3e2-49a3-8454-c8115b300257"}
            }], [{
                "componentName": "UFlexLayout",
                "containerId": "0ab64e70-1e30-44cd-8499-191ddcf04548",
                "backgroundColor": "",
                "flexDirection": "row",
                "boxNumber": 1,
                "gap": 1,
                "containerScale": [],
                "containerBackground": [],
                "minHeight": 0,
                "maxHeight": 100,
                "width": 100,
                "minWidth": 10,
                "maxWidth": 100,
                "justifyContent": "stretch",
                "alignItems": "center",
                "childHoverEffect": "none",
                "borderStyle": "solid",
                "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                "animate": "",
                "hoverEffect": "none",
                "position": "static",
                "float": "none",
                "containerScale0": 1,
                "childNodes": [[{
                    "componentName": "UText",
                    "containerId": "9bbf5fd3-66b6-49ab-a95b-38a91fcd04dc",
                    "width": 100,
                    "minWidth": 10,
                    "maxWidth": 100,
                    "content": "Links",
                    "color": "rgba(159, 159, 159, 1)",
                    "textAlignType": "end",
                    "fontSize": "revert",
                    "fontWeight": "normal",
                    "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                    "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 1, "marginBottom": 0},
                    "animate": "",
                    "hoverEffect": "none",
                    "position": "static",
                    "float": "none"
                }]],
                "mountedCallBack": {"type": "event", "event": "", "eventId": "bb0d3d26-b737-4866-8e5e-6b6f1cbe2f8f"},
                "clickChildCallBack": {"type": "event", "event": "", "eventId": "cd714107-89f8-40f7-af34-49cd13d0319d"}
            }]],
            "containerScale0": 1,
            "borderWidth": 0,
            "borderColor": "",
            "borderShow": [],
            "borderStyle": "solid",
            "containerScale1": 1,
            "mountedCallBack": {"type": "event", "event": "", "eventId": "b1deabb8-5acc-4c03-8a99-831061da5502"},
            "clickChildCallBack": {"type": "event", "event": "", "eventId": "73589b5e-a60c-42f5-95bc-cf19ce7b1e9e"}
        }]],
        "mountedCallBack": {"type": "event", "event": "", "eventId": "381e35f9-523e-46a4-aacd-b95fa94e8edc"},
        "clickChildCallBack": {"type": "event", "event": "", "eventId": "1b6cfe55-f465-4a3e-92ad-df408a519d7a"}
    }, {
        "componentName": "UFlexLayout",
        "containerId": "2e9e4b47-5167-434b-93ba-126ab0bc89bf",
        "backgroundColor": "rgba(0, 0, 0, 1)",
        "flexDirection": "row",
        "boxNumber": 1,
        "gap": 1,
        "containerScale": [],
        "containerBackground": [],
        "minHeight": 10,
        "maxHeight": 100,
        "width": 100,
        "minWidth": 10,
        "maxWidth": 100,
        "justifyContent": "stretch",
        "alignItems": "stretch",
        "childHoverEffect": "none",
        "borderStyle": "solid",
        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": "0"},
        "animate": [],
        "hoverEffect": "none",
        "position": "static",
        "float": "none",
        "childNodes": [[{
            "componentName": "UFlexLayout",
            "containerId": "11d2ca5b-034b-4d04-b2a1-92b550986180",
            "backgroundColor": "",
            "flexDirection": "row",
            "boxNumber": 2,
            "gap": 1,
            "containerScale": [],
            "containerBackground": [],
            "minHeight": 10,
            "maxHeight": 100,
            "width": 100,
            "minWidth": 10,
            "maxWidth": 67,
            "justifyContent": "stretch",
            "alignItems": "stretch",
            "childHoverEffect": "none",
            "borderStyle": "solid",
            "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
            "containerMargin": {"marginLeft": "auto", "marginRight": "auto", "marginTop": 0, "marginBottom": "2"},
            "animate": "",
            "hoverEffect": "none",
            "position": "static",
            "float": "none",
            "containerScale0": 1,
            "containerScale1": 4,
            "childNodes": [[{
                "componentName": "UText",
                "containerId": "ae152359-af69-4ed9-9ab4-1c0a890b342e",
                "width": 100,
                "minWidth": 10,
                "maxWidth": 100,
                "content": "Oriental Victoria Energ",
                "color": "rgba(159, 159, 159, 1)",
                "textAlignType": "start",
                "fontSize": "large",
                "fontWeight": "normal",
                "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                "animate": "",
                "hoverEffect": "none",
                "position": "static",
                "float": "none"
            }, {
                "componentName": "UText",
                "containerId": "16b4d3ed-7f0e-4905-871b-26b2a67e52f7",
                "width": 100,
                "minWidth": 10,
                "maxWidth": 100,
                "content": "E&T Co., Ltd (OVET)",
                "color": "rgba(159, 159, 159, 1)",
                "textAlignType": "start",
                "fontSize": "large",
                "fontWeight": "normal",
                "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                "animate": [],
                "hoverEffect": "none",
                "position": "static",
                "float": "none"
            }, {
                "componentName": "UText",
                "containerId": "ddeaebef-c1eb-46e2-b945-08fbaa5b7a8b",
                "width": 100,
                "minWidth": 10,
                "maxWidth": 100,
                "content": "All Rights Reserved",
                "color": "rgba(159, 159, 159, 1)",
                "textAlignType": "start",
                "fontSize": "large",
                "fontWeight": "normal",
                "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                "animate": "",
                "hoverEffect": "none",
                "position": "static",
                "float": "none"
            }], [{
                "componentName": "UFlexLayout",
                "containerId": "df598965-d846-4fd2-bb71-bc44ef09de9a",
                "backgroundColor": "",
                "flexDirection": "row",
                "boxNumber": 2,
                "gap": 1,
                "containerScale": [],
                "containerBackground": [],
                "minHeight": 10,
                "maxHeight": 100,
                "width": 100,
                "minWidth": 10,
                "maxWidth": 100,
                "justifyContent": "space-between",
                "alignItems": "stretch",
                "childHoverEffect": "none",
                "borderStyle": "solid",
                "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                "animate": "",
                "hoverEffect": "none",
                "position": "static",
                "float": "none",
                "containerScale0": 1,
                "containerScale1": 1,
                "childNodes": [[{
                    "componentName": "UText",
                    "containerId": "47c8c1b2-b0a6-4f13-baae-ed5119e48db6",
                    "width": 100,
                    "minWidth": 10,
                    "maxWidth": 100,
                    "content": "hello world",
                    "color": "rgba(159, 159, 159, 1)",
                    "textAlignType": "start",
                    "fontSize": "large",
                    "fontWeight": "normal",
                    "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                    "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                    "animate": "",
                    "hoverEffect": "none",
                    "position": "static",
                    "float": "none"
                }, {
                    "componentName": "UText",
                    "containerId": "ddf6e65d-6e83-4382-9e78-14cdc926ca98",
                    "width": 100,
                    "minWidth": 10,
                    "maxWidth": 100,
                    "content": "Mob: hello world",
                    "color": "rgba(159, 159, 159, 1)",
                    "textAlignType": "start",
                    "fontSize": "large",
                    "fontWeight": "normal",
                    "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                    "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                    "animate": "",
                    "hoverEffect": "none",
                    "position": "static",
                    "float": "none"
                }, {
                    "componentName": "UText",
                    "containerId": "08a7a0dd-59ee-4bc1-9333-c50dc4f07714",
                    "width": 100,
                    "minWidth": 10,
                    "maxWidth": 100,
                    "content": "Email: hello world",
                    "color": "rgba(159, 159, 159, 1)",
                    "textAlignType": "start",
                    "fontSize": "large",
                    "fontWeight": "normal",
                    "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                    "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                    "animate": [],
                    "hoverEffect": "none",
                    "position": "static",
                    "float": "none"
                }], [{
                    "componentName": "UFlexLayout",
                    "containerId": "047220da-d3a2-4840-b447-25ea37829f15",
                    "backgroundColor": "",
                    "flexDirection": "row",
                    "boxNumber": 1,
                    "gap": 1,
                    "containerScale": [],
                    "containerBackground": [],
                    "minHeight": 10,
                    "maxHeight": 100,
                    "width": 100,
                    "minWidth": 10,
                    "maxWidth": 100,
                    "justifyContent": "flex-end",
                    "alignItems": "stretch",
                    "childHoverEffect": "none",
                    "borderStyle": "solid",
                    "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                    "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                    "animate": "",
                    "hoverEffect": "none",
                    "position": "static",
                    "float": "none",
                    "containerScale0": 1,
                    "childNodes": [[{
                        "componentName": "ULink",
                        "containerId": "f3aa2d8e-c435-4359-ae86-07c274f6c74b",
                        "content": "Home",
                        "color": "rgba(159, 159, 159, 1)",
                        "textAlignType": "end",
                        "fontSize": "large",
                        "fontWeight": "normal",
                        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                        "animate": "",
                        "hoverEffect": "none",
                        "position": "static",
                        "float": "none",
                        "path": "/home"
                    }, {
                        "componentName": "ULink",
                        "containerId": "c958b918-df2d-4ed4-89a3-abcf7fb3ed95",
                        "content": "Service",
                        "color": "rgba(159, 159, 159, 1)",
                        "textAlignType": "end",
                        "fontSize": "large",
                        "fontWeight": "normal",
                        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                        "animate": "",
                        "hoverEffect": "none",
                        "position": "static",
                        "float": "none",
                        "path": "/service"
                    }, {
                        "componentName": "ULink",
                        "containerId": "876e0d56-25be-4b7e-85f6-9368fd204a45",
                        "content": "Track Peference",
                        "color": "rgba(159, 159, 159, 1)",
                        "textAlignType": "end",
                        "fontSize": "large",
                        "fontWeight": "normal",
                        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                        "animate": [],
                        "hoverEffect": "none",
                        "position": "static",
                        "float": "none",
                        "path": "/track-peference"
                    }, {
                        "componentName": "ULink",
                        "containerId": "c4f381e2-86cb-4a68-b26b-202f3d9327e5",
                        "content": "About us",
                        "color": "rgba(159, 159, 159, 1)",
                        "textAlignType": "end",
                        "fontSize": "large",
                        "fontWeight": "normal",
                        "containerPadding": {"paddingLeft": 0, "paddingRight": 0, "paddingTop": 0, "paddingBottom": 0},
                        "containerMargin": {"marginLeft": 0, "marginRight": 0, "marginTop": 0, "marginBottom": 0},
                        "animate": [],
                        "hoverEffect": "none",
                        "position": "static",
                        "float": "none",
                        "path": "/about-us"
                    }]],
                    "mountedCallBack": {
                        "type": "event",
                        "event": "",
                        "eventId": "7318b72f-bcfe-4f7a-9a7f-1ff70941ef66"
                    },
                    "clickChildCallBack": {
                        "type": "event",
                        "event": "",
                        "eventId": "c01c6679-94f1-44ea-b3f3-3f2065057a56"
                    }
                }]],
                "mountedCallBack": {"type": "event", "event": "", "eventId": "e5b96a9a-49e9-4330-914d-9f2395327ad7"},
                "clickChildCallBack": {"type": "event", "event": "", "eventId": "ed72e133-8c24-43ec-a093-3306492df00b"}
            }]],
            "mountedCallBack": {"type": "event", "event": "", "eventId": "0004a73c-7eb4-4dd2-b5c4-b0d7fbedebb0"},
            "clickChildCallBack": {"type": "event", "event": "", "eventId": "c6261b05-aaad-444c-a881-efe3cfb31e05"}
        }]],
        "containerScale0": 1,
        "mountedCallBack": {"type": "event", "event": "", "eventId": "f2b26f23-cd12-4414-9f96-98c8745a57ec"},
        "clickChildCallBack": {"type": "event", "event": "", "eventId": "59c0bf04-8d9a-462c-a046-195ad86b2d03"}
    }]
export default AboutUs;
