export const carThemeSetting = {
  header: [
    {
      componentName: "UGridLayout",
      containerId: "2b585150-b98d-4c7f-839b-051b1c6210ee",
      backgroundColor: "#eee",
      width: 100,
      minHeight: 38,
      columns: 3,
      rows: 3,
      justifyItems: "stretch",
      alignItems: "stretch",
      containerPadding: {
        paddingLeft: 10,
        paddingRight: 10,
        paddingTop: 5,
        paddingBottom: 5,
      },
      containerMargin: {
        marginLeft: 0,
        marginRight: 0,
        marginTop: 0,
        marginBottom: 0,
      },
      animate: "",
      position: "relative",
      borderStyle: "solid",
      childNodes: [
        [],
        [],
        [],
        [
          {
            componentName: "UIcon",
            containerId: "8fc921b5-52a1-4987-a213-d74bf6dc2787",
            icon: "Flag",
            color: "",
            size: 30,
            containerPadding: {
              paddingLeft: 10,
              paddingRight: 10,
              paddingTop: 5,
              paddingBottom: 5,
            },
            containerMargin: {
              marginLeft: 0,
              marginRight: 0,
              marginTop: 0,
              marginBottom: 0,
            },
            animate: "",
            position: "relative",
          },
          {
            componentName: "UTitle",
            containerId: "738e4670-e74a-4e3c-8a26-f9ca227952ee",
            title: "BYTZ",
            color: "#000000",
            textAlignType: "center",
            fontSize: "x-large",
            dynamicTag: "h1",
            containerPadding: {
              paddingLeft: 10,
              paddingRight: 10,
              paddingTop: 5,
              paddingBottom: 5,
            },
            containerMargin: {
              marginLeft: 0,
              marginRight: 0,
              marginTop: 0,
              marginBottom: 0,
            },
            animate: "",
            position: "relative",
          },
        ],
        [],
        [],
        [
          {
            componentName: "UText",
            containerId: "67a6a874-4cca-46c8-83a9-1ac8547cbe6f",
            content: "菜单1 菜单2 菜单3",
            textAlignType: "center",
            containerPadding: {
              paddingLeft: 10,
              paddingRight: 10,
              paddingTop: 5,
              paddingBottom: 5,
            },
            containerMargin: {
              marginLeft: 0,
              marginRight: 0,
              marginTop: 0,
              marginBottom: 0,
            },
            animate: "",
            position: "relative",
          },
        ],
        [],
        [
          {
            componentName: "UIcon",
            containerId: "5cfca45d-8e9f-43cb-9ba2-caeaf2a8046c",
            icon: "Search",
            color: "",
            size: 30,
            containerPadding: {
              paddingLeft: 10,
              paddingRight: 10,
              paddingTop: 5,
              paddingBottom: 5,
            },
            containerMargin: {
              marginLeft: 0,
              marginRight: 0,
              marginTop: 0,
              marginBottom: 0,
            },
            animate: "",
            position: "relative",
          },
        ],
      ],
    },
  ],
  footer: [
    {
      componentName: "UGridLayout",
      containerId: "dbd02a13-7f7b-4c89-b670-7da16468eaab",
      backgroundColor: "#eee",
      width: 100,
      minHeight: 18,
      columns: 3,
      rows: 3,
      justifyItems: "stretch",
      alignItems: "stretch",
      containerPadding: {
        paddingLeft: 10,
        paddingRight: 10,
        paddingTop: 5,
        paddingBottom: 5,
      },
      containerMargin: {
        marginLeft: 0,
        marginRight: 0,
        marginTop: 0,
        marginBottom: 0,
      },
      animate: "",
      position: "relative",
      borderStyle: "solid",
      childNodes: [
        [],
        [],
        [],
        [
          {
            componentName: "UText",
            containerId: "c808b0e3-2070-47fb-a623-db318473bb31",
            content: "底部菜单1",
            textAlignType: "center",
            containerPadding: {
              paddingLeft: 10,
              paddingRight: 10,
              paddingTop: 5,
              paddingBottom: 5,
            },
            containerMargin: {
              marginLeft: 0,
              marginRight: 0,
              marginTop: 0,
              marginBottom: 0,
            },
            animate: "",
            position: "relative",
          },
        ],
        [
          {
            componentName: "UText",
            containerId: "a4711b22-eabe-4de9-a98d-78d5a7464a8e",
            content: "底部菜单2",
            textAlignType: "center",
            containerPadding: {
              paddingLeft: 10,
              paddingRight: 10,
              paddingTop: 5,
              paddingBottom: 5,
            },
            containerMargin: {
              marginLeft: 0,
              marginRight: 0,
              marginTop: 0,
              marginBottom: 0,
            },
            animate: [],
            position: "relative",
          },
        ],
        [
          {
            componentName: "UText",
            containerId: "22b7fbf8-b621-4ea8-939b-d741f9f7614e",
            content: "底部菜单3",
            textAlignType: "center",
            containerPadding: {
              paddingLeft: 10,
              paddingRight: 10,
              paddingTop: 5,
              paddingBottom: 5,
            },
            containerMargin: {
              marginLeft: 0,
              marginRight: 0,
              marginTop: 0,
              marginBottom: 0,
            },
            animate: "",
            position: "relative",
          },
        ],
        [
          {
            componentName: "UText",
            containerId: "93536838-efab-4707-ab37-5fb46698a54a",
            content: "copyright©",
            textAlignType: "center",
            containerPadding: {
              paddingLeft: 10,
              paddingRight: 10,
              paddingTop: 5,
              paddingBottom: 5,
            },
            containerMargin: {
              marginLeft: 0,
              marginRight: 0,
              marginTop: 0,
              marginBottom: 0,
            },
            animate: "",
            position: "relative",
          },
        ],
        [
          {
            componentName: "UIcon",
            containerId: "49b9e0d1-3e74-4c9e-afd1-91548876fe69",
            icon: "ChromeFilled",
            color: "",
            size: 20,
            containerPadding: {
              paddingLeft: 10,
              paddingRight: 10,
              paddingTop: 5,
              paddingBottom: 5,
            },
            containerMargin: {
              marginLeft: 0,
              marginRight: 0,
              marginTop: 0,
              marginBottom: 0,
            },
            animate: "",
            position: "relative",
          },
        ],
        [
          {
            componentName: "UIcon",
            containerId: "6b2cd011-9736-433e-bbe7-0b2a6ec285f1",
            icon: "PhoneFilled",
            color: "",
            size: 20,
            containerPadding: {
              paddingLeft: 10,
              paddingRight: 10,
              paddingTop: 5,
              paddingBottom: 5,
            },
            containerMargin: {
              marginLeft: 0,
              marginRight: 0,
              marginTop: 0,
              marginBottom: 0,
            },
            animate: "",
            position: "relative",
          },
        ],
      ],
    },
  ],
  bodyFontFamily: "'Lora', serif",
};
